[package]
name = "colerr"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[dependencies]
libc = "*"
env_logger = "*"
docopt = "*"
rustc-serialize = "*"
mioco = { git="https://github.com/dpc/mioco", rev="88b464e" }
nix = "*"
